name: Actions Artifacts Example

on:
  push:
    branches: [ master ]

jobs:
       
  archive-build-artifacts:
    runs-on: windows-latest
    steps:

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
        
      - name: step 2 - Add artifacts to publish to the temp folder
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
deploy:
    runs-on: windows-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
   
