name: Actions Artifacts Example

on:
  push:
    branches: [ master , dinith-fix]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      
#       - name: See where we are
#       - run: ls -l 
#       - run: cd ./build
#       - run: ls -l

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
# deploy:
#     runs-on: windows-latest
#     # When application is successfully tested and build has been generated
#     # Then we can start with deployment
#     needs: build
#     steps:
#       # Download previously shared build
#       - name: Get artifact
#         uses: actions/download-artifact@v1
#         with:
#           name: react-github-actions-build
   
